name: CI
'on':
  push:
    branches:
      - master
      - main
      - '*/ci'
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    # These two checkout steps check out:
    #
    # - `curl_fuzzer` at the current ref
    # - `curl` at HEAD of the default branch
    #
    # under the `fuzz` directory.
    - name: Checkout curl fuzzer
      uses: actions/checkout@v3
      with:
        path: fuzz/curl_fuzzer
    - name: Checkout curl
      uses: actions/checkout@v3
      with:
        repository: curl/curl
        path: fuzz/curl

    # Now that the two codebases are checked out under `fuzz`,
    # use the CIFuzz steps to test them. To do this we pass
    # `project-src-path`, which overrides the codebases that
    # get checked out in the google/ossfuzz curl Dockerfile.
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'curl'
        dry-run: false
        project-src-path: fuzz

    # Finally, run the fuzzers. This isn't parallelizable so will
    # take a while.
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'curl'
        fuzz-seconds: 2400
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
